swagger: #接口注解文档
  basepackage: com.billow.system.api #必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    developer: lyongtao123@126.com #api开发者
    description: learn-shop 提供的Restful APIs #api描述
spring:
  application:
    name: learn-shop-admin-system #客户端名称
  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
    static-locations: file:///D:/project/IDEAProjects/learn/learn-shop-ui-admin
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    bus:
      trace:
        enabled: true #开启消息跟踪

security:
  sessions: NEVER
  oauth2:
    client:
      client-id: webapp
      client-secret: webapp
      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/oauth/token_key
      user-info-uri: http://127.0.0.1:8811/user
  basic:
    enabled: false #获取用户信息的地址
#      access-token-uri: http://learn-shop-public-auth/uaa/oauth/token #请求令牌的地址
#      user-authorization-uri: http://learn-shop-public-auth/uaa/oauth/authorize #请求认证的地址
#    resource:
#      jwt: #认证服务器要先启动，不然会报错
#        key-uri: http://learn-shop-public-auth/uaa/oauth/token_key #解析jwt令牌所需要密钥的地址
#      user-info-uri: http://learn-shop-public-auth/uaa/user #获取用户信息的地址
#      prefer-token-info: false
#management:
#  security:
#    enabled: false #刷新时，关闭安全验证

#security:
#  sessions: NEVER
#  oauth2:
#    resource:
#      jwt:
#        keyValue: |
#            -----BEGIN PUBLIC KEY-----
#            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhiiifKv6Otf5PyqIE+LQ
#            EiJRRh6q8piPY9Okq+RfRu9Bue0D8hq7aFxcgkLZ6Bg9CAS+w1KdaE5MMeOCVVxv
#            rpRETzVpAsh6GL5nBc679jSqMzjr3V4uty46ilL4VHKSxlZh5Nmz5EMHPI5iwpNs
#            8U5n3QiwsTk514FXad54xPSPH3i/pDzGSZHrVcwDVaOKn7gFiIqP86vkJB47JZv8
#            T6P5RK7Rj06zoG45DMGWG3DQv6o1/Jm4IJQWj0AUD3bSHqzXkPr7qyMYvkE4kyMH
#            6aVAsAYMxilZFlJMv2b8N883gdi3LEeOJo8zZr5IWyyROfepdeOL7UkAXddAj+dL
#            WQIDAQAB
#            -----END PUBLIC KEY-----