swagger: #接口注解文档
  basepackage: com.billow.system.api #必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    developer: lyongtao123@126.com #api开发者
    description: learn-shop 提供的Restful APIs #api描述
spring:
  application:
    name: learn-shop-admin-system #客户端名称
  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
    static-locations: file:///D:/project/IDEAProjects/learn/learn-shop-ui-admin
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    bus:
      trace:
        enabled: true #开启消息跟踪
security:
  sessions: NEVER
  oauth2:
    client:
      client-id: learn-shop-admin-system
      client-secret: learn-shop-admin-system
      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize #请求认证的地址
      access-token-uri: http://127.0.0.1:9999/oauth/token #请求令牌的地址
    resource:
#      jwt:
#        key-uri: http://127.0.0.1:9999/oauth/token_key #解析jwt令牌所需要密钥的地址
      user-info-uri: http://127.0.0.1:9999/user #获取用户信息的地址
      prefer-token-info: false
  basic:
    enabled: false
server:
  context-path: /learn-shop-admin-system

#security:
#  sessions: NEVER
#  oauth2:
#    client:
#      client-id: webapp
#      client-secret: webapp
#      user-authorization-uri: http://127.0.0.1:8771/auth-server/oauth/authorize #请求认证的地址
#      access-token-uri: http://127.0.0.1:8771/auth-server/oauth/token #请求令牌的地址
#    resource:
#      jwt:
#        key-uri: http://127.0.0.1:8771/auth-server/oauth/token_key #解析jwt令牌所需要密钥的地址
#      user-info-uri: http://127.0.0.1:8771/auth-server/user #获取用户信息的地址
#  basic:
#    enabled: false