server:
  port: ${config.core.order.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}

spring:
  application:
    name: ${config.core.order.spring.application.name} #客户端名称

feign:
  hystrix:
    enabled: ${config.admin.user.feign.hystrix.enabled}

words: 123,688,sldfjo,ioweur