server:
  port: ${config.core.order.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}

spring:
  application:
    name: ${config.core.order.spring.application.name} #客户端名称
  cloud:
    stream:
      bindings:
        output: #channelName，生产者
          binder: learnMQ #使用名称为learnMQ的环境
          destination: ${config.mq.orderToUser.orderStatus} #指定了消息获取的目的地，对应于MQ就是 exchange

feign:
  hystrix:
    enabled: ${config.admin.user.feign.hystrix.enabled} #启动熔断器