swagger: #接口注解文档
  basepackage: com.billow.order.api #必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    description: learn-shop 提供的Restful APIs #api描述
    contact:
      developer: billow #api开发者
      url: https://github.com/Xiao-Y/learn
      email: lyongtao123@126.com #api开发者

spring:
  application:
    name: learn-shop-core-order #客户端名称
  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
    static-locations: file:///D:/project/IDEAProjects/learn/learn-shop-ui-core
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update