server:
  port: ${config.core.order.server.port}

swagger: #接口注解文档
  basepackage: com.ft.controller #扫描的包，必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    developer: lyongtao123@126.com #api开发者
    description: learn-shop 提供的RESTful APIs #api描述

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
      status-page-url: http://localhost:${server.port}/swagger-ui.html # api文档页面

spring:
  application:
    name: ${config.core.order.spring.application.name} #客户端名称
  cloud:
    stream:
      binders:
        learnMQ:
          type: ${config.mq.type}
          environment:
            spring:
              rabbitmq:
                host: ${comfig.mq.host} #rabbitMQ服务器地址
                port: ${config.mq.port}  #rabbitMQ服务器端口
                username: ${config.mq.username}
                password: ${config.mq.password}
                virtual-host: ${config.mq.virtual-host}
      bindings:
        output: #channelName，生产者
          binder: learnMQ #使用名称为learnMQ的环境
          destination: ${config.mq.orderToUser.orderStatus} #指定了消息获取的目的地，对应于MQ就是 exchange

feign: #远程连接
  hystrix: #熔断器配置
    enabled: ${config.admin.user.feign.hystrix.enabled} #启动熔断器