swagger: #接口注解文档
  basepackage: com.billow.api #必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    developer: lyongtao123@126.com #api开发者
    description: learn-shop 提供的Restful APIs #api描述

spring:
  application:
    name: learn-shop-core-product #客户端名称
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update