server:
  port: ${config.public.job.server.port}

swagger: #接口注解文档
  basepackage: com.billow.controller #扫描的包，必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    developer: lyongtao123@126.com #api开发者
    description: learn-shop 提供的Restful APIs #api描述

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone} #注册中心地址
  instance:
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html # api文档页面

spring:
  application:
    name: ${config.public.job.spring.application.name} #客户端名称
  cloud:
    stream: #mq连接配置
      binders:
        learnMQ:
          type: ${config.mq.type}
          environment:
            spring:
              rabbitmq:
                host: ${config.mq.host} #rabbitMQ服务器地址
                port: ${config.mq.port}  #rabbitMQ服务器端口
                username: ${config.mq.username}
                password: ${config.mq.password}
                virtual-host: ${config.mq.virtual-host}
      bindings:
        outSysEventPublish: #channelName，生产者,系统事务处理,待发布
          binder: learnMQ #使用名称为learnMQ的环境
          destination: ${config.mq.tx.SysEventPublish} #指定了消息获取的目的地，对应于MQ就是 exchange
        sysEventProcess: #channelName，生产者,系统事务处理,待处理
          binder: learnMQ #使用名称为learnMQ的环境
          destination: ${config.mq.tx.SysEventProcessBase} #指定了消息获取的目的地，对应于MQ就是 exchange
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
#日志配置
#logging:
#  level:
#    root: INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
#    com.itmuch.youran.persistence: ERROR