eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone} #注册中心地址
  instance:
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/index.html # tx监控文档页面
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  application:
    name: tx-manager #客户端名称，tx-manager不得修改
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/