swagger: #接口注解文档
  basepackage: com.billow.api #必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    developer: lyongtao123@126.com #api开发者
    description: learn-shop 提供的Restful APIs #api描述

spring:
  application:
    name: learn-shop-admin-user #客户端名称
  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
    static-locations: file:///D:/project/IDEAProjects/learn/learn-shop-ui-admin
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    bus:
      trace:
        enabled: true #开启消息跟踪
#安全配置
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8771/uaa/user
      prefer-token-info: false
management:
  security:
    enabled: false #刷新时，关闭安全验证