server:
  port: ${config.admin.user.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone} #注册中心地址

spring:
  application:
    name: ${config.admin.user.spring.application.name} #客户端名称

words: ${config.eureka.instance.hostname}