server:
  port: ${config.zipkin.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
    status-page-url: http://localhost:${server.port}/zipkin/ # zipkin文档页面
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  application:
    name: ${config.zipkin.spring.application.name}
  cloud:
    stream: #mq连接配置
      binders:
        learnMQ:
          type: ${config.mq.type}
          environment:
            spring:
              rabbitmq:
                host: ${config.mq.host} #rabbitMQ服务器地址
                port: ${config.mq.port}  #rabbitMQ服务器端口
                username: ${config.mq.username}
                password: ${config.mq.password}
                virtual-host: ${config.mq.virtual-host}
      bindings:
        sleuth: #channelName，消费者
          binder: learnMQ #使用名称为learnMQ的环境
          contentType: text/plain
          destination: sleuth #指定了消息获取的目的地，对应于MQ就是 exchange
          consumer:
            exchangeType: fanout #指定该主题的类型为广播模式
            autoBindDlq: true #消费失败的消息放入dlq队列
            republishToDlq: true

  sleuth:
    enabled: false #不对自己采集
    sampler:
      percentage: 0.1 #数据采集比例，为1是全采集，影响性能

zipkin:
  storage: #表示zipkin数据存储方式是 mysql
    type: mysql