server:
  port: ${config.zipkin.server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
    status-page-url: http://localhost:${server.port}/zipkin/ # zipkin文档页面
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  application:
    name: learn-cloud-zipkin
  rabbitmq:
    host: ${config.mq.host} #rabbitMQ服务器地址
    port: ${config.mq.port}  #rabbitMQ服务器端口
    username: ${config.mq.username}
    password: ${config.mq.password}
    virtual-host: ${config.mq.virtual-host}
  sleuth:
    enabled: false #不对自己采集
    sampler:
      percentage: 1 #数据采集比例，为1是全采集，影响性能

zipkin:
  storage: #表示zipkin数据存储方式是 mysql
    type: mysql