server:
  port: 9411

spring:
  application:
    name: cloud-zipkin
  cloud:
    stream: #mq连接配置
      binders:
        learnMQ:
          type: ${config.mq.type}
          environment:
            spring:
              rabbitmq:
                host: ${comfig.mq.host} #rabbitMQ服务器地址
                port: ${config.mq.port}  #rabbitMQ服务器端口
                username: ${config.mq.username}
                password: ${config.mq.password}
                virtual-host: ${config.mq.virtual-host}
      bindings:
        sleuth: #channelName，消费者
          binder: learnMQ #使用名称为learnMQ的环境
          contentType: text/plain
          destination: sleuth #指定了消息获取的目的地，对应于MQ就是 exchange
          consumer:
            exchangeType: fanout #指定该主题的类型为广播模式
            autoBindDlq: true #消费失败的消息放入dlq队列
            republishToDlq: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    initialize: true
    continue-on-error: true

  sleuth:
    enabled: false
    sampler:
      percentage: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/zipkin/ # zipkin文档页面
    prefer-ip-address: true

zipkin:
  storage: #表示zipkin数据存储方式是 mysql
    type: mysql