server:
  port: ${config.turbine.server.port}

spring:
  application:
    name: learn-cloud-turbine

turbine:
  app-config: ${config.turbine.app-config} #配置Eureka中的serviceId列表，表明监控哪些服务
  aggregator:
    cluster-config: ${config.turbine.aggregator.cluster-config}
  cluster-name-expression: ${config.turbine.cluster-name-expression}

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
#   status-page-url: http://localhost:${server.port}/zipkin/ # zipkin文档页面
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}