swagger: #接口注解文档
  basepackage: com.billow.zuul.api #必须要有 GetMapping，PostMapping...
  service:
    name: ${spring.application.name} #api名称
    version: 1.0
    description: 警告：此API仅用于测试，禁止任何商业用途，否则一切后果自行承担！！！ #api描述
    contact:
      developer: billow #api开发者
      url: https://github.com/Xiao-Y/learn
      email: lyongtao123@126.com #api开发者
server:
  port: ${config.zuul.server.port}

spring:
  application:
    name: learn-cloud-zuul
#  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
#    static-locations: file:///D:/GitHub/learn/learn-shop-ui-admin/dist
eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

# 如果路由方式是serviceId的方式，那么ribbon的生效，如果是url的方式，则zuul.host开头的生效
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 10000
zuul:
  host:
    socket-timeout-millis: 50000
    connect-timeout-millis: 10000
##  #添加代理头
#  add-proxy-headers: true
#  #敏感头信息
  sensitive-headers:
  routes:
    #服务认证和授权
    public-auth:
      path: /public-auth/**
      serviceId: learn-shop-public-auth
    #系统相关
    admin-system:
      path: /admin-system/**
      strip-prefix: false
      serviceId: learn-shop-admin-system
    #用户相关
    admin-user:
      path: /admin-user/**
      serviceId: learn-shop-admin-user
    #订单相关
    core-order:
      path: /core-order/**
      serviceId: learn-shop-core-order
    #商品相关
    core-product:
      path: /core-product/**
      serviceId: learn-shop-core-product
    public-job:
      path: /public-job/**
      serviceId: learn-shop-public-job
# Logging configuration
logging:
  level: DEBUG