server:
  port: ${config.zuul.server.port}

spring:
  application:
    name: ${config.zuul.spring.application.name}
  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
    static-locations: file:///D:/project/IDEAProjects/learn/learn-shop-ui-admin
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

zuul:
  routes:
    #系统相关
    admin-system:
      path: /admin-system/**
      serviceId: ${config.admin.system.spring.application.name}
    #用户相关
    admin-user:
      path: /admin-user/**
      serviceId: ${config.admin.user.spring.application.name}
    #订单相关
    core-order:
      path: /core-order/**
      serviceId: ${config.core.order.spring.application.name}
    #商品相关
    core-product:
      path: /core-product/**
      serviceId: ${config.core.product.spring.application.name}

billow:
  security:
    token:
      expiration-time: 10 # 分钟 1440
      refresh-exp-time: 30 # 分钟 2880
      issuer: "" #签发者
      signing-key: billow #密钥

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
    com.billow.security: DEBUG