server:
  port: ${config.zuul.server.port}

spring:
  application:
    name: learn-cloud-zuul
  resources: #指定静态资源路径，多个使用英文逗号隔开。如：html,js.jsp
    static-locations: file:///D:/project/IDEAProjects/learn/learn-shop-ui-admin
  jpa: #JPA配置
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign: #远程连接
  hystrix: #熔断器配置
    enabled: true #启动熔断器
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #Hystrix 是否启用超时时间
        isolation:
          thread:
            #Hystrix 断路器的超时时间，默认是1s，断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE
# 如果路由方式是serviceId的方式，那么ribbon的生效，如果是url的方式，则zuul.host开头的生效
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 10000
zuul:
  host:
    socket-timeout-millis: 50000
    connect-timeout-millis: 10000
  #添加代理头
  add-proxy-headers: true
  #敏感头信息
  sensitive-headers:
  routes:
    #服务认证和授权
    uaa:
      path: /uaa/**
      serviceId: learn-shop-public-auth
    #系统相关
    admin-system:
      path: /admin-system/**
      serviceId: learn-shop-admin-system
    #用户相关
    admin-user:
      path: /admin-user/**
      serviceId: learn-shop-admin-user
    #订单相关
    core-order:
      path: /core-order/**
      serviceId: learn-shop-core-order
    #商品相关
    core-product:
      path: /core-product/**
      serviceId: learn-shop-core-product
    public-job:
      path: /public-job/**
      serviceId: learn-shop-public-job

security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://learn-shop-public-auth/uaa/oauth/token
      user-authorization-uri: http://learn-shop-public-auth/uaa/oauth/authorize
    resource:
      user-info-uri: http://learn-shop-public-auth/uaa/user
      prefer-token-info: false
management:
  security:
    enabled: false
#billow:
#  security:
#    token:
#      expiration-time: 10 # 分钟 1440
#      refresh-exp-time: 30 # 分钟 2880
#      issuer: "" #签发者
#      signing-key: billow #密钥

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
    com:
      billow:
        security: DEBUG
        filter: DEBUG