server:
  port: ${config.zuul.server.port}

spring:
  application:
    name: ${config.zuul.spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: ${config.eureka.client.serviceUrl.defaultZone}
  instance:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

zuul:
  routes:
    #用户相关
    admin-user:
      path: /admin-user/**
      serviceId: ${config.admin.user.spring.application.name}
    #订单相关
    core-order:
      path: /core-order/**
      serviceId: ${config.core.order.spring.application.name}